version: '2.2'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: rp3
    restart: "unless-stopped"
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL=redis://cache:6379/4"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://rp3:rp3@db/rp3"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  frontend:
    build: ./docker/nginx/
    image: rp3-frontend
    restart: "unless-stopped"
    ports:
      - "80"
      - "443"
  cache:
    image: docker.uclv.cu/redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: docker.uclv.cu/postgres:12.4
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=rp3"
      - "POSTGRES_PASSWORD=rp3"
      - "POSTGRES_DB=rp3"
    ports:
      - "5432:5432"
  pgadmin:
    image: docker.uclv.cu/dpage/pgadmin4:6
    restart: "unless-stopped"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafael.martinez@upr.edu.cu"
      PGADMIN_DEFAULT_PASSWORD: "rp3"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
  mq:
    image: docker.uclv.cu/rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
  search:
    image: public.ecr.aws/opensearchproject/opensearch:2.17.1
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"
  opensearch-dashboards:
    image: public.ecr.aws/opensearchproject/opensearch-dashboards:2.17.1
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
